### ISSUE TITLE
Shaded JAR contains outdated Jackson

### ISSUE THREAD

**Issue by ksobolew** [linkedin/linkedin-calcite#85]
The shaded JAR of linkedin's `calcite-core` contains several Jackson libraries at versions 2.13.2, which is relatively new (but still has some CVE's atached to it), and `jackson-databind` 2.9.10.8, which is pretty old at this point. Since this is a shaded JAR, we who depend on this library can't force a newer version of Jackson without re-forking the library and rebuilding the JAR, so hereby I'm asking to bump the version of Jackson. Thanks!

**Comment by aastha25** [comment]
Thanks @ksobolew for bringing it up. I have created a PR https://github.com/linkedin/linkedin-calcite/pull/89 for the upgrade. It should be checked in soon.
